<a href="https://colab.research.google.com/github/songqsh/MA2210/blob/main/.src/bfs_discussion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import packages
import numpy as np
import numpy.linalg as la
np.set_printoptions(suppress=True)
import itertools

In [2]:
# input augmented form
A = np.array([[1.,0,1,0, 0], [1.,3,0,1, 0], [2, 1, 0, 0, 1]])
b = np.array([4, 15, 10])
print(A, b)

[[1. 0. 1. 0. 0.]
 [1. 3. 0. 1. 0.]
 [2. 1. 0. 0. 1.]] [ 4 15 10]


In [3]:
# A function solving for bfs
# inputs:
#   list_of_bv: an index list of basic variables
#   mat_A: 2d numpy array for matrix A
#   vec_b: 1d numpy array with the length equal to row number of A
# return:
#   either basic solution or error message
def bfs(list_of_bv, mat_A, vec_b):
    try:
        basic_solution = la.solve(mat_A[:, list_of_bv], vec_b)

        if min(basic_solution) < 0:
            raise (ValueError('Infeasible solution'))
        return basic_solution

    except la.LinAlgError as err:
        return err

    except ValueError as err:
        return err

In [4]:
bvs = itertools.combinations(range(5), 3)

for bv1 in bvs:
    print(f'checking bv {bv1}')
    res1 = bfs(bv1, A, b)
    print(f'--- {res1}')

checking bv (0, 1, 2)
--- [3. 4. 1.]
checking bv (0, 1, 3)
--- [4. 2. 5.]
checking bv (0, 1, 4)
--- Infeasible solution
checking bv (0, 2, 3)
--- Infeasible solution
checking bv (0, 2, 4)
--- Infeasible solution
checking bv (0, 3, 4)
--- [ 4. 11.  2.]
checking bv (1, 2, 3)
--- Infeasible solution
checking bv (1, 2, 4)
--- [5. 4. 5.]
checking bv (1, 3, 4)
--- Singular matrix
checking bv (2, 3, 4)
--- [ 4. 15. 10.]
