In [2]:
# import packages
import numpy as np

In [3]:
# matrix input
A = np.array([[2,3], [1, -5]])
B = np.array([[4,3,6], [1,-2,3.]])
print(f'The matrix A is \n {A}')
print(f'The matrix B is \n {B}')

The matrix A is 
 [[ 2  3]
 [ 1 -5]]
The matrix B is 
 [[ 4.  3.  6.]
 [ 1. -2.  3.]]


In [4]:
# transpose 
print(f'transpose of A is {A.T}')
print(f'transpose of B is {B.T}')

transpose of A is [[ 2  1]
 [ 3 -5]]
transpose of B is [[ 4.  1.]
 [ 3. -2.]
 [ 6.  3.]]


In [5]:
# matrix multiplication
print(B.T@A.T)

[[11. -1.]
 [ 0. 13.]
 [21. -9.]]


In [7]:
# inverse of a matrix
C = np.linalg.inv(A)
print(f'matrix C is \n {C}')
print(f'A times C is \n {A@C}')

matrix C is 
 [[ 0.38461538  0.23076923]
 [ 0.07692308 -0.15384615]]
A times C is 
 [[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]
