<a href="https://colab.research.google.com/github/songqsh/MA2210/blob/main/src/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import packages

import numpy as np
import numpy.linalg as la

In [3]:
# matrix input
A = np.array([[2,3], [1, -5]])
B = np.array([[4,3,6], [1,-2,3.]])
print(A)
print(B)

[[ 2  3]
 [ 1 -5]]
[[ 4.  3.  6.]
 [ 1. -2.  3.]]


In [6]:
# transpose 
print(A.T)
print(B.T)

[[ 2  1]
 [ 3 -5]]
[[ 4.  1.]
 [ 3. -2.]
 [ 6.  3.]]


In [8]:
# matrix multiplication
print(B.T@A.T)

[[11. -1.]
 [ 0. 13.]
 [21. -9.]]
