In [1]:
# import packages
import numpy as np
np.set_printoptions(suppress=True)

Solve the following linear system by pivoting:
$$
x_1 + 2 x_2 - x_3  = 4$$
$$- x_1 - x_2 + 2x_3  = 1$$
$$x_1 \quad \quad \quad + x_3  = 6$$


In [2]:
def pivot(A, i, j):
  A[i] = A[i]/A[i,j] #scale to get one in (i,j)
  n_rows, _ = A.shape
  for k in range(n_rows):
    if k==i:
      continue # skip i-row
    A[k] = A[k] - A[i]*A[k,j] # replacement to get zero

In [3]:
#matrix input
M = np.array([[1,2,-1,4.],[-1.,-1, 2,1], [1.,0,1, 6]])
M

array([[ 1.,  2., -1.,  4.],
       [-1., -1.,  2.,  1.],
       [ 1.,  0.,  1.,  6.]])

In [4]:
pivot(M,1,1)
M

array([[-1.,  0.,  3.,  6.],
       [ 1.,  1., -2., -1.],
       [ 1.,  0.,  1.,  6.]])

In [5]:
pivot(M,0,0)
M

array([[ 1., -0., -3., -6.],
       [ 0.,  1.,  1.,  5.],
       [ 0.,  0.,  4., 12.]])

In [6]:
pivot(M,2,2)
M

array([[1., 0., 0., 3.],
       [0., 1., 0., 2.],
       [0., 0., 1., 3.]])