<a href="https://colab.research.google.com/github/songqsh/MA2210/blob/main/src/pivotizing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import packages
import numpy as np
import numpy.linalg as la
np.set_printoptions(suppress=True)
import itertools

In [2]:
def pivot(A, i, j):
  A[i] = A[i]/A[i,j] #scale to get one in (i,j)
  n_rows, _ = A.shape
  for k in range(n_rows):
    if k==i:
      continue # skip i-row
    A[k] = A[k] - A[i]*A[k,j] # replacement to get zero

In [9]:
#matrix input
M = np.array([[1,2,-1,4.],[-1.,-1, 2,1], [1.,0,1, 6]])

In [10]:
pivot(M,1,1)
M

array([[-1.,  0.,  3.,  6.],
       [ 1.,  1., -2., -1.],
       [ 1.,  0.,  1.,  6.]])

In [11]:
pivot(M,0,0)
M

array([[ 1., -0., -3., -6.],
       [ 0.,  1.,  1.,  5.],
       [ 0.,  0.,  4., 12.]])

In [12]:
pivot(M,2,2)
M

array([[1., 0., 0., 3.],
       [0., 1., 0., 2.],
       [0., 0., 1., 3.]])