# Pivoting

In [23]:
# import packages
import numpy as np
np.set_printoptions(suppress=True)

In [24]:
# pivoting with (i,j)
def pivoting(A, i, j):
    A[i] = A[i] / A[i, j]  # scale to get one in (i,j)
    n_rows, _ = A.shape
    for k in range(n_rows):
        if k == i:
            continue  # skip i-row
        A[k] = A[k] - A[i] * A[k, j]  # replacement to get zero

## Ex.

Solve the following linear system by pivoting:
$$
x_1 + 2 x_2 - x_3  = 4$$
$$- x_1 - x_2 + 2x_3  = 1$$
$$x_1 \quad \quad \quad + x_3  = 6$$


In [30]:
#matrix input
M = np.array([[1,2,-1,4.],[-1.,-1, 2,1], [1.,0,1, 6]])
print(f'{M}')

[[ 1.  2. -1.  4.]
 [-1. -1.  2.  1.]
 [ 1.  0.  1.  6.]]


In [31]:
for i in range(3):
    pivoting(M, i, i)
    print(f'----\n {M}')

----
 [[ 1.  2. -1.  4.]
 [ 0.  1.  1.  5.]
 [ 0. -2.  2.  2.]]
----
 [[ 1.  0. -3. -6.]
 [ 0.  1.  1.  5.]
 [ 0.  0.  4. 12.]]
----
 [[1. 0. 0. 3.]
 [0. 1. 0. 2.]
 [0. 0. 1. 3.]]


## Ex.
Consider the following linear system:
$$
\begin{array}{ll}
x_1 + 3 x_3 & = 2\\
x_2 - 3 x_4 & = 3\\
-2x_2+3x_3+2x_4 & = 1\\
3x_1 + 7x_4 & = -5
\end{array}
$$
- Write its augmented matrix
- Pivot augmented matrix on $(i, i)$ entry sequentially for $i = 1,2,3,4$
- What is the solution?