# Pivoting

In [24]:
# import packages
import numpy as np
np.set_printoptions(suppress=True)

In [31]:
# pivoting with (i,j)
def pivoting(A_mat, row_i, col_i):
    try:
        A_mat[row_i] = A_mat[row_i] / A_mat[row_i, col_i]  # scale to get one in (row_i,col_i)
    except ZeroDivisionError as err:
        return err
    n_rows, _ = A_mat.shape
    for k in range(n_rows):
        if k == row_i:
            continue  # skip i-row
        A_mat[k] = A_mat[k] - A_mat[row_i] * A_mat[k, col_i]  # replacement to get zero
    return 1

## Ex.

Solve the following linear system by pivoting:
$$
x_1 + 2 x_2 - x_3  = 4$$
$$- x_1 - x_2 + 2x_3  = 1$$
$$x_1 \quad \quad \quad + x_3  = 6$$


In [32]:
#matrix input
M = np.array([[1,2,-1,4.],[-1.,-1, 2,1], [1.,0,1, 6]])
print(f'{M}')

[[ 1.  2. -1.  4.]
 [-1. -1.  2.  1.]
 [ 1.  0.  1.  6.]]


In [33]:
for i in range(3):
    pivoting(M, i, i)
    print(f'----\n {M}')

----
 [[ 1.  2. -1.  4.]
 [ 0.  1.  1.  5.]
 [ 0. -2.  2.  2.]]
----
 [[ 1.  0. -3. -6.]
 [ 0.  1.  1.  5.]
 [ 0.  0.  4. 12.]]
----
 [[1. 0. 0. 3.]
 [0. 1. 0. 2.]
 [0. 0. 1. 3.]]


In [34]:
#matrix input
M = np.array([[1,2,-1,4.],[-1.,-1, 2,1], [0.,1,1, 6]])
print(f'{M}')

[[ 1.  2. -1.  4.]
 [-1. -1.  2.  1.]
 [ 0.  1.  1.  6.]]


In [35]:
pivoting(M, 0, 0)
pivoting(M, 1, 1)

1

In [36]:
M

array([[ 1.,  0., -3., -6.],
       [ 0.,  1.,  1.,  5.],
       [ 0.,  0.,  0.,  1.]])

In [37]:
pivoting(M, 2, 2)

/Users/qsong/PycharmProjects/ib1/venv/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.
/Users/qsong/PycharmProjects/ib1/venv/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


1