<a href="https://colab.research.google.com/github/songqsh/MA2210/blob/main/src/quadratic_programming_bfs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Transport problem
From Section 8.1



In [1]:
# import packages
import numpy as np
import numpy.linalg as la
np.set_printoptions(suppress=True)
import itertools

In [2]:
A = np.array([[4, -4, 1, -1, 0, 0, 15],
              [-4, 8., 2., 0, -1, 0, 30],
              [1, 2, 0, 0, 0, 1, 30]])
print(f'{A}')

[[ 4. -4.  1. -1.  0.  0. 15.]
 [-4.  8.  2.  0. -1.  0. 30.]
 [ 1.  2.  0.  0.  0.  1. 30.]]


In [21]:
for bv in itertools.product([0,3],[1,4],[2,5]):
  try:
    bs = la.solve(A[:,bv], A[:,-1])
    print(f'bv is {bv} and bs is {bs}')
  except:
    print(f'bv is {bv} and  it is singular')

bv is (0, 1, 2) and bs is [12.  9.  3.]
bv is (0, 1, 5) and bs is [15.   11.25 -7.5 ]
bv is (0, 4, 2) and bs is [  30. -360. -105.]
bv is (0, 4, 5) and bs is [  3.75 -45.    26.25]
bv is (3, 1, 2) and bs is [-120.   15.  -45.]
bv is (3, 1, 5) and bs is [-30.     3.75  22.5 ]
bv is (3, 4, 2) and  it is singular
bv is (3, 4, 5) and bs is [-15. -30.  30.]


In [15]:
bv = [3,4,2]
try:
  bs = la.solve(A[:,bv], A[:,-1])
  print(f'bv is {bv} and bs is {bs}')
except:
  print(f'bv is {bv} and  it is singular')

bv is [3, 4, 2] and  it is singular


In [8]:
bv = [0,4,2]
bs = la.solve(A[:,bv], A[:,-1])
print(f'bv is {bv} and bs is {bs}')

bv is [0, 4, 2] and bs is [  30. -360. -105.]


In [9]:
bv = [0,1,5]
bs = la.solve(A[:,bv], A[:,-1])
print(f'bv is {bv} and bs is {bs}')

bv is [0, 1, 5] and bs is [15.   11.25 -7.5 ]


In [10]:
bv = [3,1,5]
bs = la.solve(A[:,bv], A[:,-1])
print(f'bv is {bv} and bs is {bs}')

bv is [3, 1, 5] and bs is [-30.     3.75  22.5 ]


In [11]:
bv = [3,4,5]
bs = la.solve(A[:,bv], A[:,-1])
print(f'bv is {bv} and bs is {bs}')

bv is [3, 4, 5] and bs is [-15. -30.  30.]


In [12]:
bv = [0,4,5]
bs = la.solve(A[:,bv], A[:,-1])
print(f'bv is {bv} and bs is {bs}')

bv is [0, 4, 5] and bs is [  3.75 -45.    26.25]
